### ISSUE TITLE
doesn't compile on 1.1.0-dev

### ISSUE THREAD

**Issue by ishworgurung** [jstasiak/rust-socket#3]
Hello,
JFYI

``` rust
% cargo build --verbose
   Compiling socket v0.0.6
     Running `rustc /home/isg/.cargo/registry/src/github.com-1ecc6299db9ec823/socket-0.0.6/src/lib.rs --crate-name socket --crate-type lib -g -C metadata=e0b88cd6ee5adbbd -C extra-filename=-e0b88cd6ee5adbbd --out-dir /tmp/socketfoo-rust/target/debug/deps --emit=dep-info,link -L dependency=/tmp/socketfoo-rust/target/debug/deps -L dependency=/tmp/socketfoo-rust/target/debug/deps --extern libc=/tmp/socketfoo-rust/target/debug/deps/liblibc-2eda841eb12a3090.rlib -Awarnings`
       Fresh libc v0.1.8
/home/isg/.cargo/registry/src/github.com-1ecc6299db9ec823/socket-0.0.6/src/lib.rs:25:5: 25:18 error: unresolved import `std::num::Int`. There is no `Int` in `std::num`
/home/isg/.cargo/registry/src/github.com-1ecc6299db9ec823/socket-0.0.6/src/lib.rs:25 use std::num::Int;
                                                                                         ^~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `socket`.

Caused by:
  Process didn't exit successfully: `rustc /home/isg/.cargo/registry/src/github.com-1ecc6299db9ec823/socket-0.0.6/src/lib.rs --crate-name socket --crate-type lib -g -C metadata=e0b88cd6ee5adbbd -C extra-filename=-e0b88cd6ee5adbbd --out-dir /tmp/socketfoo-rust/target/debug/deps --emit=dep-info,link -L dependency=/tmp/socketfoo-rust/target/debug/deps -L dependency=/tmp/socketfoo-rust/target/debug/deps --extern libc=/tmp/socketfoo-rust/target/debug/deps/liblibc-2eda841eb12a3090.rlib -Awarnings` (exit code: 101)

% rustc --version
rustc 1.1.0-dev (feac9f1c7 2015-05-12) (built 2015-05-12)
```

**Comment by ishworgurung** [comment]
Nevermind https://github.com/jethro/rust-socket/commit/61cc6b48a0816e86bc07a7f3e035546181b11e0a fixes it

**Comment by jstasiak** [comment]
Thank you for the report, this is fixed by 0f2ac075c61600429f51469350d0f8409fef45a7 now
